#! /usr/bin/python3
from  future_lib import*

args = sys.argv
current_dir = args[0][:args[0].rfind('/')]

try:
    data_file = open(current_dir + '/data.json')
except:
    print("Welcome to Future!\n\n"
          , "Type 'future help' to see help message.\n", sep='')

    data_file = open(current_dir + '/data.json', 'w')
    data_file.write('{"events": {}, "cycles": [], "window": 30}')
    exit(0)

data_string = data_file.read();
data_file.close()

data = json.loads(data_string)

future = Future(data)

if (len(args) == 1):
    future.show()
elif args[1] == 'add':
    future.add(args[1:])
elif args[1] == 'rm':
    future.rm(args[1:])
elif args[1] == 'set':
    future.set_window(args[1:])
elif args[1] == 'cycle':
    future.cycle(args[1:])
elif args[1] == 'stop':
    future.stop_cycle(args[1:])
elif args[1] == 'cycles':
    future.print_cycles()
else:
    future.help()

data_string = json.dumps(future.data())
data_file = open(current_dir + '/data.json', 'w')
data_file.write(data_string)
