#!/usr/bin/python3
from  ogr_lib import*

args = sys.argv
current_dir = args[0][:-4]
data_file = open(current_dir + '/data.json')
data_string = data_file.read();
data_file.close()
data = json.loads(data_string)
ogr = Ogr(data)


if (len(args) == 1):
    ogr.show()
elif (args[1] == "date"):
    print(datetime.date.today())
elif args[1] == 'open':
    ogr.open(args)
elif args[1] == 'close':
    ogr.close(args)
elif args[1] == 'add':
    ogr.add(args)
elif args[1] == 'rm':
    ogr.rm(args)
elif args[1] == 'clear':
    ogr.clear(args)
else:
    ogr.help()


data_string = json.dumps(data)
data_file = open(current_dir + '/data.json', 'w')
data_file.write(data_string)
