#!/usr/bin/python3
from  ogr_lib import*

args = sys.argv
current_dir = args[0][:-4]
try:
    data_file = open(current_dir + '/data.json')
except:
    print("Welcome to Ogr!\n\nTry typing 'open tomorrow'"
    , " then 'add to 0' and then type some event.\n"
    , "Type 'ogr help' to see help message.\n", sep='')
    data_file = open(current_dir + '/data.json', 'w')
    data_file.write('{"dates": [], "events": {}, "weekdays": {}, "cycles": [], "window": 30}')
    exit(0)
data_string = data_file.read();
data_file.close()
data = json.loads(data_string)
ogr = Ogr(data)


if (len(args) == 1):
    ogr.show()
elif (args[1] == "date"):
    print(datetime.date.today())
elif args[1] == 'open':
    if len(args) < 3:
        print("No arguments");
    else:
        ogr.open(args)
elif args[1] == 'close':
    ogr.close(int(args[2]))
elif args[1] == 'add':
    ogr.add(args)
elif args[1] == 'rm':
    ogr.rm(args)
elif args[1] == 'clear':
    ogr.clear(args)
elif args[1] == 'window':
    ogr.show_window()
elif args[1] == 'set':
    ogr.set_window(args)
elif args[1] == 'cycle':
    ogr.cycle(args)
elif args[1] == 'stop':
    ogr.stop_cycle(args)
elif args[1] == 'show':
    ogr.show_cycles(args)
elif args[1] == 'help':
    ogr.help()
else:
    ogr.help()


data_string = json.dumps(ogr.data())
data_file = open(current_dir + '/data.json', 'w')
data_file.write(data_string)
